name: Python package

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Run tests
        run: |
          python -m pip install tox
          python -m tox -e py

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-wheel-${{ matrix.python }}
          path: dist/*.whl

      - uses: codecov/codecov-action@v3
        with:
          files: .tox/coverage.xml
          name: python-nistitl
        if: matrix.python == '3.12' && matrix.os == 'ubuntu-latest'

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run sphinx
        run: |
          python -m pip install tox
          python -m tox -e docs
